export const OPEN_SHIPMENT_NOTES_MODAL = "OPEN_SHIPMENT_NOTES_MODAL";
export const CLOSE_SHIPMENT_NOTES_MODAL = "CLOSE_SHIPMENT_NOTES_MODAL";

export const OPEN_VIEW_SHIPMENT_MODAL = "OPEN_VIEW_SHIPMENT_MODAL";
export const CLOSE_VIEW_SHIPMENT_MODAL = "CLOSE_VIEW_SHIPMENT_MODAL";

export const OPEN_SHIPMENT_NOTES_ADD_NOTES_MODAL = "OPEN_SHIPMENT_NOTES_ADD_NOTES_MODAL";
export const CLOSE_SHIPMENT_NOTES_ADD_NOTES_MODAL = "CLOSE_SHIPMENT_NOTES_ADD_NOTES_MODAL";

export const OPEN_SHIPMENT_NOTES_SEND_EMAIL_MODAL = "OPEN_SHIPMENT_NOTES_SEND_EMAIL_MODAL";
export const CLOSE_SHIPMENT_NOTES_SEND_EMAIL_MODAL = "CLOSE_SHIPMENT_NOTES_SEND_EMAIL_MODAL";

export const OPEN_DISPATCH_MENU_DIALOG_MODAL = "OPEN_DISPATCH_MENU_DIALOG_MODAL";
export const CLOSE_DISPATCH_MENU_DIALOG_MODAL = "CLOSE_DISPATCH_MENU_DIALOG_MODAL";

export const OPEN_MODIFY_PICKUP_DIALOG_MODAL = "OPEN_MODIFY_PICKUP_DIALOG_MODAL";
export const CLOSE_MODIFY_PICKUP_DIALOG_MODAL = "CLOSE_MODIFY_PICKUP_DIALOG_MODAL";

export const OPEN_BOL_DETAIL_MODAL = "OPEN_BOL_DETAIL_MODAL";
export const CLOSE_BOL_DETAIL_MODAL = "CLOSE_BOL_DETAIL_MODAL";

export const OPEN_TRACKING_SHIPMENT_MODAL = "OPEN_TRACKING_SHIPMENT_MODAL";
export const CLOSE_TRACKING_SHIPMENT_MODAL = "CLOSE_TRACKING_SHIPMENT_MODAL";

export const OPEN_VOID_SHIPMENT_MODAL = "OPEN_VOID_SHIPMENT_MODAL";
export const CLOSE_VOID_SHIPMENT_MODAL = "CLOSE_VOID_SHIPMENT_MODAL";
export const CLOSE_CANCEL_SHIPMENT_MODAL = "CLOSE_CANCEL_SHIPMENT_MODAL";

export const TOGGLE_VIEW_COLUMN_SETTING = 'TOGGLE_VIEW_COLUMN_SETTING';
export const RESTORE_COLUMN_SETTING = 'RESTORE_COLUMN_SETTING';

export const CHANGE_COLUMN_ORDER_FREIGHT_HISTORY = 'CHANGE_COLUMN_ORDER_FREIGHT_HISTORY';

export const OPEN_FORWARDING_ROUTE = 'OPEN_FORWARDING_ROUTE';
export const CLOSE_FORWARDING_ROUTE = 'CLOSE_FORWARDING_ROUTE';

export const UPDATE_POPULATION_OBJ = 'UPDATE_POPULATION_OBJ';