export const defaultValues = {
    parcel_type: ['LTL'],
    totalWeight: 0,
    // origin_country: {value: 'United States of America', label: 'United States of America', code: 'US'},
    // origin_city: 'Mountain View',
    // origin_state: 'CA',
    // origin_post_code: '91043',
    // destination_country: {value: 'United States of America', label: 'United States of America', code: 'US'},
    // destination_city: 'New York',
    // destination_state: 'NY',
    // destination_post_code: '10036',
    load_item: [{
        // dimension_length: '5',
        // dimension_width: '5',
        // dimension_height: '2',
        // weight: '15.4',
        weight_unit: {value: 'Lbs', label: 'Lbs'},
        // commodity: {value: 25, label: "Description 10011", nmfc: "50"},
        // commodity_nmfc: '50',
        // class: {value: '50', label: '50'},
        type: {value: 'Pallets', label: 'Pallets'},
        // units: 1,
        is_hazmat: false,
        is_stackable: true,
    }],
    insurance_amount: null,
    accessorial: [],
    pickupDate: new Date()
};