export const freightHistoryColumnSettings = [
    {column:"actions",                  is_active: true,    disable_hide: true,     label: 'Actions'},
    {column:"quoteId",                  is_active: false,   disable_hide: false,    label: 'Quote ID'},
    {column:"quoteNumber",              is_active: true,    disable_hide: true,     label: 'Quote Number'},
    {column:"displayStatus",            is_active: true,    disable_hide: true,     label: 'Status'},
    {column:"note",                     is_active: true,    disable_hide: false,    label: 'Note'},
    {column:"transactionDate",          is_active: true,    disable_hide: false,    label: 'Transaction Date'},
    {column:"serviceType",              is_active: true,    disable_hide: false,    label: 'Service Type'},
    {column:"shipDate",                 is_active: true,    disable_hide: false,    label: 'Ship Date'},
    {column:"senderName",               is_active: true,    disable_hide: false,    label: 'Sender'},
    {column:"receiverName",             is_active: true,    disable_hide: false,    label: 'Receiver'},
    {column:"customerBoLNumber",        is_active: true,    disable_hide: true,     label: 'Bol Number'},
    {column:"unitType",                 is_active: true,    disable_hide: false,    label: 'Unit Type'},
    {column:"numberOfItems",            is_active: true,    disable_hide: false,    label: 'Handling Units'},
    {column:"customerProNumber",        is_active: true,    disable_hide: true,     label: 'Pro Number'},
    {column:"transitTime",              is_active: true,    disable_hide: false,    label: 'Est. Transit Time'},
    {column:"pickupDateTime",           is_active: true,    disable_hide: false,    label: 'Pickup Date'},
    {column:"carrierName",              is_active: true,    disable_hide: false,    label: 'Carrier'},
    {column:"displayInsuredAmount",     is_active: true,    disable_hide: false,    label: 'Protection Premium'},
    {column:"deliveryDate",             is_active: true,    disable_hide: false,    label: 'Est. Delivery'},
    {column:"totalWeight",              is_active: true,    disable_hide: false,    label: 'Weight'},
    {column:"accessorials",             is_active: true,    disable_hide: false,    label: 'Accessorials'},
    {column:"displayQuotedAmount",      is_active: true,    disable_hide: false,    label: 'Quoted Amount'},
]