export type SavedQuotesResponse = {
    id: number | null,
    uuid: string | null,
    success: boolean,
    errors: null,
    collection: boolean,
    elementCount: number,
    pageSize: number,
    pageNumber: number,
    pageCount: number,
    sortField: string,
    sortOrder: string,
    data: ShipmentTypes[],
    dataType: string,
    message: string | null
}

export type ShipmentTypes = {
    providerId:  number,
    shipmentId:  number,
    displayStatus:  string,
    dispatched: boolean,
    providerStatusCode:  number,
    statusEnumName:  string,
    hotShipment:  boolean,
    note: string | null,
    serviceType:  string,
    shipDate:  string,
    senderName:  string,
    senderCompanyName:  string,
    senderAddress1: string,
    senderAddress2: string | null,
    senderAddress3: string | null,
    senderCity: string,
    senderPostalCode: string,
    senderStateCode: string,
    senderCountryCode: string,
    receiverName: string | null,
    receiverCompanyName: string,
    receiverAddress1: string,
    receiverAddress2: string | null,
    receiverAddress3: string | null,
    receiverCity: string ,
    receiverPostalCode: string,
    receiverStateCode:string,
    receiverCountryCode:string,
    issuedBoLNumber: string,
    customerBoLNumber:  string,
    unitType: string | null,
    numberOfItems: number,
    issuedProNumber: string,
    customerProNumber: string,
    pickupDateTime: string | null,
    carrierName: string,
    carrierPhone: string | null,
    carrierEmail: string | null,
    carrierWebAddress: string | null,
    tariffDescription: string,
    insuredAmount: number,
    displayInsuredAmount: number,
    deliveryDate: string | null,
    totalWeight: number,
    quotedAmount: number,
    displayQuotedAmount: string,
    tag:  null,
    providerQuoteId: string,
    expired: boolean,
}

export type quoteItemTypes = {
        id: number,
        quoteItem: {
            providerId: null | string,
            providerQuoteId: string,
            providerQuoteItemId: string,
            carrierId: null | string,
            carrierName: string,
            carrierSCAC: null | string,
            carrierLogo: null | string,
            tariffIdentifier: null | string,
            tariffDescription: null | string,
            tariffOwner: null | string,
            isBlueGrace: null | boolean,
            serviceType: string,
            accountNumber: null | string,
            baseRate: null,
            markupApplied: null,
            price: number,
            displayPrice: null,
            quoteNumber: null | string,
            transitTime: string,
            originPhone: null,
            destinationPhone: null,
            message: null | string,
            bestPriceSortIndex: number,
            quickestSortIndex: number,
            markupToApply: null
        },
        freightQuoteRequest: {
            uuid: string,
            serviceTypes: null,
            serviceType: null,
            customerType: null,
            customerAccountNumber: null,
            originCity: string,
            originState: string,
            originAddressCode: string,
            originCountry: null,
            destinationCity: string,
            destinationState: string,
            destinationAddressCode: string,
            destinationCountry: null,
            canGoOnRefrigeratedVan: null,
            fullTruckLoad: null,
            standardSize: null,
            linealFootRate: null,
            totalLinealFoot: null,
            stackType: null,
            serviceLevel: null,
            needHaulaway: null,
            wgFieldDestroy: null,
            freightItems: [
                {
                    id: null,
                    weight: number,
                    dimensions: {
                        length: number,
                        width: number,
                        height: number
                    },
                    measurementType: string,
                    numberOfUnits: number,
                    hazmat: boolean,
                    classCode: string,
                    nmfcCode: string,
                    commodityDescription: string,
                    packageType: string,
                    description: null,
                    reference: null
                }
            ],
            accessorials: [any],
            customerCode: string,
            franchiseCode: null,
            insuranceInformation: null
        },
        accessorialCount: number,
        palletCount: number,
        jsonQuote: null,
        createdTime: string
}
